# pvc.yaml (created per execution with unique name)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-<EXECUTION_ID>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi