apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depl
  annotations:
    recreate-pod-timestamp: "{{ now | unixEpoch }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
      annotations:
        recreate-pod-timestamp: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: secrets-sa
      containers:
        - name: executions
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
          volumeMounts:
            - name: executions-secrets
              mountPath: /etc/executions
              readOnly: true
      volumes:
        - name: executions-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-secrets
      imagePullSecrets:
        - name: docker-registry-secret
      nodeSelector:
        kubernetes.io/arch: amd64

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
    - name: ws
      protocol: TCP
      port: 5003
      targetPort: 5003
