# pvc.yaml (created per execution with unique name)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: execution-pvc-<EXECUTION_ID>
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi