apiVersion: v1
kind: Pod
metadata:
  name: execution-bootstrap-<EXECUTION_ID>
spec:
  containers:
    - name: setup
      image: execution-controller:latest
      env:
        - name: EXTRACT_DIR
          value: <UUID> # unique per execution/project
        - name: BLINQ_TOKEN
          valueFrom:
            secretKeyRef:
              name: blinq-secrets
              key: token
        - name: EXECUTION_ID
          value: "<EXECUTION_ID>"
      volumeMounts:
        - name: shared-volume
          mountPath: /app/shared
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: execution-pvc-<EXECUTION_ID>
  restartPolicy: Never
