apiVersion: v1
kind: Pod
metadata:
  name: setup-<EXECUTION_ID>
  labels:
    version-hash: "v<BUILD_ID>"
spec:
  containers:
    - name: setup
      image: execution-controller:jqic81
      imagePullPolicy: Never
      env:
        - name: EXTRACT_DIR
          value: <EXTRACT_DIR>
        - name: BLINQ_TOKEN
          value: <BLINQ_TOKEN>
        - name: EXECUTION_ID
          value: "<EXECUTION_ID>"
        - name: NODE_ENV_BLINQ
          value: "<NODE_ENV_BLINQ>"
      volumeMounts:
        - name: shared-volume
          mountPath: /app/shared
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: pvc-<EXECUTION_ID>
  restartPolicy: Never
