# pvc.yaml (created per execution with unique name)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-681f5cec9074438ede56819f
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi