# pvc.yaml (created per execution with unique name)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-681c9703caf20a72a22cbe49
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi