# pvc.yaml (created per execution with unique name)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-681e11c6f92a259ef51da7f0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi