# pvc.yaml (created per execution with unique name)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-681def26d7b4790c227aca1b
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi