apiVersion: v1
kind: Pod
metadata:
  name: setup-681def26d7b4790c227aca1b
  labels:
    version-hash: "v${BUILD_ID}"
spec:
  containers:
    - name: setup
      image: execution-controller:dev
      imagePullPolicy: Never
      env:
        - name: EXTRACT_DIR
          value: 68185297cbe2c9f67291631d
        - name: BLINQ_TOKEN
          valueFrom:
            secretKeyRef:
              name: blinq-secrets
              key: token
        - name: EXECUTION_ID
          value: "681def26d7b4790c227aca1b"
        - name: CACHE_BUSTER
          value: "{{timestamp}}"
      volumeMounts:
        - name: shared-volume
          mountPath: /app/shared
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: pvc-681def26d7b4790c227aca1b
  restartPolicy: Never
