apiVersion: v1
kind: Pod
metadata:
  name: setup-681c9703caf20a72a22cbe49
spec:
  containers:
    - name: setup
      image: execution-controller:dev
      imagePullPolicy: Never
      env:
        - name: EXTRACT_DIR
          value: 68185297cbe2c9f67291631d
        - name: BLINQ_TOKEN
          valueFrom:
            secretKeyRef:
              name: blinq-secrets
              key: token
        - name: EXECUTION_ID
          value: "681c9703caf20a72a22cbe49"
      volumeMounts:
        - name: shared-volume
          mountPath: /app/shared
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: pvc-681c9703caf20a72a22cbe49
  restartPolicy: Never
