apiVersion: v1
kind: Pod
metadata:
  name: setup-6819b2976e53a8e793d1ab3e
spec:
  containers:
    - name: setup
      image: execution-controller:dev
      imagePullPolicy: Never
      env:
        - name: EXTRACT_DIR
          value: 68185297cbe2c9f67291631d
        - name: BLINQ_TOKEN
          valueFrom:
            secretKeyRef:
              name: blinq-secrets
              key: token
        - name: EXECUTION_ID
          value: "6819b2976e53a8e793d1ab3e"
      volumeMounts:
        - name: shared-volume
          mountPath: /app/shared
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: pvc-6819b2976e53a8e793d1ab3e
  restartPolicy: Never
