apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{.Release.Name}}-secrets
spec:
  provider: aws
  parameters:    
    objects: |
      - objectName: "dev/executions/env"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MONGO_URI"
            objectAlias: "MONGO_URI"
          - path: "BACKEND_SOCKET_URL"
            objectAlias: "BACKEND_SOCKET_URL"
          - path: "EXPRESS_SERVER_PORT"
            objectAlias: "EXPRESS_SERVER_PORT"
          - path: "SOCKET_PORT"
            objectAlias: "SOCKET_PORT"
          
  secretObjects:
    - secretName: {{.Release.Name}}-secrets
      type: Opaque
      data:
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: BACKEND_SOCKET_URL
          key: BACKEND_SOCKET_URL
        - objectName: EXPRESS_SERVER_PORT
          key: EXPRESS_SERVER_PORT
        - objectName: SOCKET_PORT
          key: SOCKET_PORT
        