name: Executions CI Dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server
          push: true
          tags: blinqio/executions-service-dev:latest

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
  
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
  
      - name: Connect to EKS cluster and run Helm commands
        run: |
          aws eks --region eu-north-1 update-kubeconfig --name execution-manager-dev
          helm upgrade executions ./charts/charts-dev/executions-chart --install